### ISSUE TITLE
TypeError: 'NoneType'

### ISSUE THREAD

**Issue by theodosiout** [CheckPoint-APIs-Team/ExportObjects#6]
Traceback (most recent call last):
  File "export_groups.py", line 14, in <module>
    get_objects("groups", fields, dependency_solver_args)
  File "C:\ExportObjects\get_objects.py", line 128, in get_objects
    dependency_solver_args=dependency_solver_args)
  File "C:\ExportObjects\get_objects.py", line 112, in get_data
    dependency_loader = DependencyLoader(data, singular_type, client=client)
  File "C:\ExportObjects\get_objects.py", line 732, in __init__
    client=client) for item in list]
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 836, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 848, in __init__
    parents_keys=parents_keys, client=client).uid)
  File "C:\ExportObjects\get_objects.py", line 804, in __init__
    res = dependency_loader.get_full_details(self.uid)
  File "C:\ExportObjects\get_objects.py", line 774, in get_full_details
    obj = self.client.api_call("show-object", {"uid": uid, "details-level": "full"}).data["object"]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by chkp-niram** [comment]
Hey @theodosiout ,
Does the issue still persists? If so, we would like to pin-point the problematic object that causes that error.
Can you find from the API logs or otherwise what object is queried in the last API call before the failure? 
That should be the last "show-object" that fails.

**Comment by chkp-niram** [comment]
Hey @theodosiout, i'm closing the issue for now. if the issue persists please open a new issue with the relevant information
